[package]
name = "test-basic-http"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = { version = "1.0.218", features = ["derive"] }
diesel = { version = "2.1.0",  features = ["postgres", "r2d2", "chrono"]}
dotenv = "0.15.0"